def word_score(word):
    '''
    A function named word_score that takes a parameter word. 

    Returns the point generated by a word while playinh the scrabble game.
    '''

    dict_ = {1: ['A', 'E','I', 'L', 'N', 'O', 'R', 'S', 'T' ,'U'], 
    2: ['D', 'G'], 3: ['B', 'C', 'M', 'P'], 4: ['F', 'H', 'V', 'W', 'Y'], 
    5:['k'], 8: ['J', 'X'], 10: ['Q','Z']}
    res = [k for k,v in dict_.items() for char in word if char.upper() in v]
    return sum(res)
